@Library('jenkins-va@feature/android') _

node {
  String args = sh(script: "test -d /home/jenkins/sonar-scanner && echo '1' || echo '0' ", returnStdout: true).trim() == '1' ?
    '-v /home/jenkins/sonar-scanner:/home/jenkins/sonar-scanner' : ''

  withDockerContainer([
    image: 'circleci/android:api-28',
    args : args
  ]) {
    androidPipeline([
      vcsHostingProvider       : 'GITHUB',
      vcsRepo                  : 'valueadd-poland/Rest-Countries-Android',
      projectName              : 'android_rest_countries',
      slackTeamChannel         : [channel: 'android-builds', domain: 'valueadd-team']
    ])
  }
}